rb_controller:
  ros__parameters:
    signal_mode: zero

rb_safety:
  ros__parameters:
    input_command_topic: /rb/command_raw
    output_command_topic: /rb/command_safe
    input_joint_states_topic: /rb/joint_states
    safety_enabled: true
    safe_mode_action: zero_effort
    effort_abs_max_default: 8.0
    joint_limit_margin_rad: 0.05
    input_timeout_sec: 0.2
    tilt_limit_roll_rad: 10.0
    tilt_limit_pitch_rad: 10.0
    imu_topic: /rb/imu
    joint_limits:
      left_hip_pitch_joint:
        lower: -2.349999711181
        upper: 3.049999885799
      right_hip_pitch_joint:
        lower: -2.349999711181
        upper: 3.049999885799
      torso_joint:
        lower: -2.618000003262
        upper: 2.618000003262
      left_hip_roll_joint:
        lower: -0.259999973074
        upper: 2.529999839782
      left_hip_yaw_joint:
        lower: -2.749999849008
        upper: 2.749999849008
      left_knee_joint:
        lower: -0.334889977074
        upper: 2.544899693449
      left_ankle_pitch_joint:
        lower: -0.67999996799
        upper: 0.729999951929
      left_ankle_roll_joint:
        lower: -0.261799970366
        upper: 0.261799970366
      right_hip_roll_joint:
        lower: -2.529999839782
        upper: 0.259999973074
      right_hip_yaw_joint:
        lower: -2.749999849008
        upper: 2.749999849008
      right_knee_joint:
        lower: -0.334889977074
        upper: 2.544899693449
      right_ankle_pitch_joint:
        lower: -0.67999996799
        upper: 0.729999951929
      right_ankle_roll_joint:
        lower: -0.261799970366
        upper: 0.261799970366
      left_shoulder_pitch_joint:
        lower: -2.967099675807
        upper: 2.792499905264
      right_shoulder_pitch_joint:
        lower: -2.967099675807
        upper: 2.792499905264
      left_shoulder_roll_joint:
        lower: -1.588199951361
        upper: 2.251499768787
      left_shoulder_yaw_joint:
        lower: -2.618000003262
        upper: 2.618000003262
      left_elbow_pitch_joint:
        lower: -0.226799974951
        upper: 3.420799793854
      left_elbow_roll_joint:
        lower: -2.094299894384
        upper: 2.094299894384
      left_five_joint:
        lower: -1.839999968215
        upper: 0.300000003502
      left_three_joint:
        lower: -1.839999968215
        upper: 0.300000003502
      left_zero_joint:
        lower: -0.52359797665
        upper: 0.52359797665
      left_six_joint:
        lower: -1.839999968215
        upper: 0.0
      left_four_joint:
        lower: -1.839999968215
        upper: 0.0
      left_one_joint:
        lower: -0.999999945094
        upper: 1.200000014007
      left_two_joint:
        lower: 0.0
        upper: 1.839999968215
      right_shoulder_roll_joint:
        lower: -2.251499768787
        upper: 1.588199951361
      right_shoulder_yaw_joint:
        lower: -2.618000003262
        upper: 2.618000003262
      right_elbow_pitch_joint:
        lower: -0.226799974951
        upper: 3.420799793854
      right_elbow_roll_joint:
        lower: -2.094299894384
        upper: 2.094299894384
      right_five_joint:
        lower: -0.300000003502
        upper: 1.839999968215
      right_three_joint:
        lower: -0.300000003502
        upper: 1.839999968215
      right_zero_joint:
        lower: -0.52359797665
        upper: 0.52359797665
      right_six_joint:
        lower: 0.0
        upper: 1.839999968215
      right_four_joint:
        lower: 0.0
        upper: 1.839999968215
      right_one_joint:
        lower: -1.200000014007
        upper: 0.999999945094
      right_two_joint:
        lower: -1.839999968215
        upper: 0.0
